<h1>Curl Songs Listing</h1>
<div class="row">
	<ul>
		<li><a href="<?php echo $this->url('songs', array('action' => 'create')) ?>">add Songs</a></li>
	</ul>	
</div>
<div class="row">
	<div class="col-xs-12 col-md-12">	
		<div class="demo-box">
			<table class="mGrid table table-bordered" id="jsondata">
				<thead>
					<tr>
						<th>Song Id</th>						
						<th>Song Title</th>
						<th></th>						
					</tr>
				</thead>
				<tbody>
					<?php foreach ($data as $key => $val): ?>			
						<tr>
							<td><?php echo $val['song_id']; ?></td>							
							<td><?php echo $val['song_title']; ?></td>
							<td>
								<a href="<?php echo $this->url('songs', array('action' => 'update', 'album_id' => $_SESSION['album']['album_id'], 'song_id' => $val['song_id'])); ?>">Edit Song</a> |
								<a href="<?php echo $this->url('songs', array('action' => 'delete', 'album_id' => $_SESSION['album']['album_id'], 'song_id' => $val['song_id'])); ?>">Delete Song</a> 																								
							</td>																																				
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>  
 </div>
