
<h1>Song Form</h1>
<?php
$album_id =	(int) $_SESSION['album']['album_id'];
$form = $this->form;

echo $this->form()->openTag($form);

$album_field = $form->get('album_id');
$album_field->setValue($album_id);
echo $this->formInput($album_field);
echo $this->formElementErrors($form->get('album_id'));

echo $this->formLabel($form->get('song_title'));
echo $this->formElement($form->get('song_title'));
echo $this->formElementErrors($form->get('song_title'));
echo '<br>';
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag($form);
